#!/usr/bin/env Rscript
args<-commandArgs(TRUE)
library(ANTsR)
j=antsImageRead("/tmp/circAjacobian.nii.gz")
circ = antsImageRead( args[1] )
circ2 = antsImageRead( args[2])
print( args[3] )
myjcalc = sum( j[ circ == 1 ] / sum( circ == 1 ) )
print(paste("Jacobian-based ratio", myjcalc ) )
myscalc = sum(  sum( circ2 == 1 )/ sum( circ == 1 ) )
print(paste("Segmentation-based ratio", myscalc ) )
print( paste("%err", 100.0 * ( 1.0-myjcalc/myscalc ) ) )
